# Site settings
title: fernandohur's blog
email: fernandohur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A coder's path to enlightment.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: fernandohur
github_username:  fhur

# Build settings
markdown: kramdown
